/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game2_graphical;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class gameMenu extends javax.swing.JFrame {
    boolean userpick = false, isclicked = false;
    game_helper game = new game_helper();
    Random rand = new Random();
    /**
     * Creates new form gameMenu
     */
    public gameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rock_btn = new javax.swing.JButton();
        reset_btn2 = new javax.swing.JButton();
        go_btn = new javax.swing.JButton();
        scissors_btn = new javax.swing.JButton();
        usermov_disp = new javax.swing.JTextField();
        compmove_disp = new javax.swing.JTextField();
        reset_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paper_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rock_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rock_btn.setText("Rock");
        rock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rock_btnActionPerformed(evt);
            }
        });

        reset_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reset_btn2.setText("Main Menu");
        reset_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btn2ActionPerformed(evt);
            }
        });

        go_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        go_btn.setText("Go!");
        go_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_btnActionPerformed(evt);
            }
        });

        scissors_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scissors_btn.setText("Scissors");
        scissors_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissors_btnActionPerformed(evt);
            }
        });

        usermov_disp.setEditable(false);
        usermov_disp.setColumns(3);
        usermov_disp.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        usermov_disp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usermov_disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermov_dispActionPerformed(evt);
            }
        });

        compmove_disp.setEditable(false);
        compmove_disp.setColumns(3);
        compmove_disp.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        compmove_disp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        compmove_disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compmove_dispActionPerformed(evt);
            }
        });

        reset_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reset_btn.setText("Reset Move");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your move:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Computer's move:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("vs.");

        paper_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paper_btn.setText("Paper");
        paper_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paper_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rock_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(go_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paper_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scissors_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(usermov_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compmove_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compmove_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usermov_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paper_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rock_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scissors_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(go_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rock_btnActionPerformed

        if (userpick == false){
            move rock = new rock();
            game.user = rock;
            userpick = true;
            compmove_disp.setText("*Unknown*");
        }
        if (userpick == true){
            usermov_disp.setText(game.user.name);
        }
    }//GEN-LAST:event_rock_btnActionPerformed

    private void reset_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btn2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to go back to the main menu?", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION){
            new homeMenu().setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_reset_btn2ActionPerformed

    private void go_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_btnActionPerformed
        // TODO add your handling code here:
        game.comp_guess = rand.nextInt(3)+1;
        game.assigncom();
        if (game.user != null){
            try {
            FileOutputStream fileOut =
            new FileOutputStream("C:\\Users\\Asus\\Desktop/employee.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(game);
            out.close();
            fileOut.close();
        } catch (IOException i) {
            i.printStackTrace();
            } 
            this.hide();
            new TimerDo().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please pick a move.", "Try again", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_go_btnActionPerformed

    private void scissors_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissors_btnActionPerformed
        // TODO add your handling code here:
        if (userpick == false){
            move scissors = new scissors();
            game.user = scissors;
            userpick = true;
            compmove_disp.setText("*Unknown*");
        }
        if (userpick == true){
            usermov_disp.setText(game.user.name);

        }
    }//GEN-LAST:event_scissors_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        userpick = false;
    }//GEN-LAST:event_reset_btnActionPerformed

    private void paper_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paper_btnActionPerformed
        // TODO add your handling code here:
        if (userpick == false){
            move paper = new paper();
            game.user = paper;
            userpick = true;
            compmove_disp.setText("*Unknown*");
        }
        if (userpick == true){
            usermov_disp.setText(game.user.name);
        }
    }//GEN-LAST:event_paper_btnActionPerformed

    private void compmove_dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compmove_dispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compmove_dispActionPerformed

    private void usermov_dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermov_dispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usermov_dispActionPerformed

    /**
     * @param args the command line arguments
     */
    void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField compmove_disp;
    private javax.swing.JButton go_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton paper_btn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton reset_btn2;
    private javax.swing.JButton rock_btn;
    private javax.swing.JButton scissors_btn;
    private javax.swing.JTextField usermov_disp;
    // End of variables declaration//GEN-END:variables
}
